import type { RewriteMode } from "@/types"

export const GENERIC_PHRASES = [
  "passionate about",
  "team player",
  "hard worker",
  "love to learn",
  "seeking opportunities",
  "looking for",
  "aspiring",
  "detail-oriented",
  "results-driven",
  "highly motivated",
] as const

export const ATS_KEYWORDS = [
  "javascript",
  "typescript",
  "react",
  "python",
  "node.js",
  "aws",
  "docker",
  "sql",
  "rest api",
  "graphql",
  "git",
  "ci/cd",
  "developed",
  "built",
  "implemented",
  "designed",
  "optimized",
  "led",
  "managed",
  "deployed",
  "architected",
  "improved",
  "reduced",
  "increased",
  "scaled",
  "automated",
  "shipped",
  "launched",
  "collaborated",
  "mentored",
  "cross-functional",
  "stakeholder",
  "github",
  "jira",
  "figma",
  "linux",
] as const

export const MODE_KEYWORD_BOOST: Record<RewriteMode, string[]> = {
  startup: [
    "product",
    "scale",
    "ownership",
    "ship",
    "iterate",
    "0-to-1",
    "growth",
    "MVP",
    "full-stack",
  ],
  faang: [
    "distributed systems",
    "algorithms",
    "metrics",
    "data-driven",
    "system design",
    "high scale",
    "latency",
    "reliability",
    "cross-functional",
  ],
  recruiter: [
    "developed",
    "built",
    "implemented",
    "optimized",
    "led",
    "shipped",
    "cross-functional",
    "stakeholder",
  ],
  internship: [
    "projects",
    "coursework",
    "eager to learn",
    "collaboration",
    "github",
    "portfolio",
    "internship",
    "new grad",
  ],
}

export const REWRITE_RATE_LIMIT = 10
export const REWRITE_COOKIE_NAME = "rewrite_count"
